export enum MedServiceEnum {
  FAMILY_MEDICINE = "Family Medicine",
  PEDIATRICS = "Pediatrics",
  GYNECOLOGY = "Gynecology",
  OBSTETRICS = "Obstetrics",
  CARDIOLOGY = "Cardiology",
  NEUROLOGY = "Neurology",
  ONCOLOGY = "Oncology",
  UROLOGY = "Urology",
  DERMATOLOGY = "Dermatology",
  ENDOCRINOLOGY = "Endocrinology",
  ORTHOPEDICS = "Orthopedics",
  TRAUMATOLOGY = "Traumatology",
  GASTROENTEROLOGY = "Gastroenterology",
  OTOLARYNGOLOGY = "Otolaryngology",
  PSYCHIATRY = "Psychiatry",
  DENTISTRY = "Dentistry",
  PRIVATE_LABORATORY = "Private Laboratory",
  DIAGNOSTIC_SERVICES = "Diagnostics Services",
}
